export const fonts = {
    NunitoRegular: require('../../assets/fonts/Nunito-Regular.ttf'),
    NunitoRegular2: require('../../assets/fonts/Nunito-VariableFont_wght.ttf'),
    NunitoBold: require('../../assets/fonts/Nunito-Bold.ttf'),
    NunitoBlack: require('../../assets/fonts/Nunito-Black.ttf'),
    NunitoBlackItalic: require('../../assets/fonts/Nunito-BlackItalic.ttf'),
    NunitoBoldItalic: require('../../assets/fonts/Nunito-BoldItalic.ttf'),
    NunitoExtraBold: require('../../assets/fonts/Nunito-ExtraBold.ttf'),
    NunitoExtraBoldItalic: require('../../assets/fonts/Nunito-ExtraBoldItalic.ttf'),
    NunitoExtraLigth: require('../../assets/fonts/Nunito-ExtraLight.ttf'),
    NunitoExtraLigthItalic: require('../../assets/fonts/Nunito-ExtraLightItalic.ttf'),
    NunitoItalic: require('../../assets/fonts/Nunito-Italic-VariableFont_wght.ttf'),
    NunitoItalic2: require('../../assets/fonts/Nunito-Italic.ttf'),
    NunitoLight: require('../../assets/fonts/Nunito-Italic.ttf'),
    NunitoLightItalic: require('../../assets/fonts/Nunito-LightItalic.ttf'),
    NunitoMedium: require('../../assets/fonts/Nunito-Medium.ttf'),
    NunitoMediumItalic: require('../../assets/fonts/Nunito-MediumItalic.ttf'),
    NunitoSemiBold: require('../../assets/fonts/Nunito-SemiBold.ttf'),
    NunitoSemiBoldItalic: require('../../assets/fonts/Nunito-SemiBoldItalic.ttf'),
}